import.java.util.Scanner;
class SWAPPING
	{
		private int a,b,c;
		public void swap(string str)
		System.out.println("enter the string:+a");
		System.out.println("enter the string:+b");
		c=a;		
		a=b;
		b=c;
		System.out.println("After Swapping : a="+a+" , b="+b); 
	}
classMAIN _SWAPPING
         {
public static void main(String args[])
                        {
		String str;
		scanner sc=new Scanner(System.in);
		str=sc.nextline();
		SWAPPING swp=new SWAPPING();
		swp.SWAPPING(a,b);
	       }
}